org: gabrielfrisancho
service: api-web-scraping

provider:
  name: aws
  runtime: python3.10
  memorySize: 1024
  timeout: 20
  region: us-east-1
  iam:
    role: arn:aws:iam::213965374161:role/LabRole

custom:
  pythonRequirements:
    dockerizePip: non-linux

functions:
  scrape_earthquakes:
    handler: scrap_table.lambda_handler
    events:
      - http:
          path: /scrape/earthquakes
          method: get
          cors: true

package:
  include:
    - ./**

resources:
  Resources:
    TablaWebScrapping:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TablaWebScrapping
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
